short_name = "ramatak"
name = "Ramatak Mobile Studion - Powered by Godot engine"
major = 3
minor = 5
patch = 1
status = "stable"
module_config = ""
year = 2022
website = "https://godotengine.org"
docs = "3.5"
